### PR TITLE
Rename neo4j-service to neo4j

### PR DESCRIPTION
**Pull request by aguynamedjoetoo**
Figured I'd help and correct an annoying bug I ran into since your playbook saved me some time today (:

Thanks!

### CODE REVIEW

**Comment by deimosfr** [comment]
Hi,

I think this has changed with versions. Can you please update the name with a variable instead to keep compatibility?

Thanks

**Comment by aguynamedjoetoo** [comment]
Sure!

I'm assuming, since the newest versions (which are the default in the playbook) assume `neo4j`  is the service name, we just put that as something,say, `neon4j_service_name` in `defaults/main.yml`? 

Or do you feel there is a better approach?

**Comment by deimosfr** [comment]
Lgtm

**Review by deimosfr — APPROVED** [review]

**Comment by deimosfr** [comment]
Thanks !

**Pull request merged**
